### ISSUE TITLE
华为mate30 5G版手机兼容性问题

### ISSUE THREAD

**Issue by jiangfangjian** [AirtestProject/AirtestIDE#613] opened 2019-11-20 04:48 UTC
**详细描述问题bug：**
IDE中已经显示了设备，但是点击‘connect’无法连接成功，左侧device窗口不显示手机界面，log有报错信息

**复现步骤：**
尝试连接即可出现

**python 版本:** `python3.7`

**操作系统:** `Windows10家庭中文版 64bit`

**手机设备信息:**
 - 手机型号:TAS-AN00
 - Android系统版本号: [Android 10]
 

**其他相关信息补充**
根据FAQ文档中的信息都有试过，兼容性列表没有该机型，此机型是华为今年最新旗舰即
- AirtestIDE版本号：V1.2.1

**截屏**
![企业微信截图_15742249088763](https://user-images.githubusercontent.com/45865616/69210281-2bbc1300-0b95-11ea-8cd7-f8b357c0b069.png)

**Comment by jiangfangjian** [comment] 2019-11-20 04:49
D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s XPL5T19A28019724 wait-for-device
D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s XPL5T19A28019724 shell getprop ro.build.version.sdk
Device:XPL5T19A28019724 updated <airtest.core.android.android.Android object at 0x000002AE5F0BF860> -> <airtest.core.android.android.Android object at 0x000002AE5F0BFC88>
D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s XPL5T19A28019724 shell ls /data/local/tmp/minicap
D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s XPL5T19A28019724 shell ls /data/local/tmp/minicap.so
install minicap
D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s XPL5T19A28019724 shell getprop ro.product.cpu.abi
D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s XPL5T19A28019724 shell getprop ro.build.version.preview_sdk
D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s XPL5T19A28019724 shell getprop ro.build.version.release
D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s XPL5T19A28019724 push D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\stf_libs\arm64-v8a\minicap /data/local/tmp/minicap
D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s XPL5T19A28019724 shell chmod 755 /data/local/tmp/minicap
D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s XPL5T19A28019724 push D:\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\stf_libs\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so /data/local/tmp/minicap.so
Traceback (most recent call last):
  File "app\plugins\device\android\android_client.py", line 162, in loadConnectedPhones
  File "app\plugins\device\android\android_phone.py", line 83, in __init__
  File "app\plugins\device\android\android_phone.py", line 111, in _initDev
  File "airtest\core\android\android.py", line 527, in display_info
    self._display_info = self.get_display_info()
  File "airtest\core\android\android.py", line 546, in get_display_info
    display_info = self.minicap.get_display_info()
  File "airtest\utils\snippet.py", line 104, in ready_func
    method()
  File "airtest\utils\snippet.py", line 115, in wrapper
    ret = func(inst, *args, **kwargs)
  File "airtest\core\android\minicap.py", line 86, in install_or_upgrade
    self.install()
  File "airtest\core\android\minicap.py", line 132, in install
    self.adb.push(path, "%s/minicap.so" % device_dir)
  File "airtest\core\android\adb.py", line 429, in push
    self.cmd(["push", local, remote], ensure_unicode=False)
  File "airtest\core\android\adb.py", line 187, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[b"adb: error: cannot stat 'D:\\AirtestIDE_2019-05-09_py3_win64\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so': No such file or directory\r\n"] stderr[b'']

ADB指令执行失败，可能需要修改部分手机设置才能使用，请访问[帮助文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html)查看如何设置。

**Comment by yimelia** [comment] 2019-11-20 06:03
duplicate of https://github.com/AirtestProject/Airtest/issues/504
安卓10暂时还没有支持，请关注上述帖子的进度以获取更新信息

**Closed as completed by yimelia** 2019-11-20 06:03 UTC
