### ISSUE TITLE
小米9 系统升级Android10后无法连接

### ISSUE THREAD

**Issue by NekoNeko404** [AirtestProject/AirtestIDE#680] opened 2020-01-06 02:49 UTC
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

(重要！问题分类)

连接失败

描述问题bug
1.小米9升级系统至android10之后无法连接AirtestIDE，报错：airtest.core.error.AdbError: stdout[b"adb: error: cannot stat 'D:\\Program Files (x86)\\AirtestIDE_2019-09-11_py3_win64\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so': No such file or directory\r\n"] stderr[b'']

airtest 版本: 1.2.2

![image](https://user-images.githubusercontent.com/17821772/71792383-804b1d00-3073-11ea-8472-cc929e9815fb.png)

![image](https://user-images.githubusercontent.com/17821772/71792500-e768d180-3073-11ea-83d6-1e827a18092b.png)

**Comment by yimelia** [comment] 2020-01-06 03:07
Duplicate of https://github.com/AirtestProject/Airtest/issues/504

**Closed as completed by yimelia** 2020-01-06 03:07 UTC
