### ISSUE TITLE
Airtest-Selenium测试web页面判断图像相关问题 

### ISSUE THREAD

**Issue by GoodbyeMercy** [AirtestProject/AirtestIDE#663] opened 2019-12-26 05:52 UTC
在使用Airtest-Selenium测试Web页面时，若要判断一些弹窗提示，若发生弹窗关闭弹窗继续执行，由于弹窗结构经常迭代修改，不想通过selenium元素定位的方式，想通过识别图像的方式判断，手机端可以使用if exists（图像元素）来判断，但貌似web端用exists时一直识别不到对应的图像，返回的结果是：
01:42:19][INFO]<airtest.core.api> Try finding:
Template(E:\Work\AirtestIDE_2019-09-11_py3_win64\webtest-db-v2.0.air\tpl1577335689903.png)
[01:42:19][DEBUG]<airtest.core.api> resize: (206, 78)->(2366, 896), resolution: (100, 100)=>(1625, 766)
[01:42:19][DEBUG]<airtest.core.api> try match with SURFMatching
[01:42:21][DEBUG]<airtest.aircv.keypoint_base> find_best_result() run time is 2.04 s.
[01:42:21][DEBUG]<airtest.core.api> try match with TemplateMatching
[01:42:21][DEBUG]<airtest.core.api> 'error: in template match, found im_search bigger than im_source.'
[01:42:21][DEBUG]<airtest.core.api> try match with BRISKMatching
[01:42:21][DEBUG]<airtest.aircv.keypoint_base> find_best_result() run time is 0.61 s.
[01:42:21][DEBUG]<airtest.core.api> match result: None
[01:42:22][DEBUG]<airtest.core.api> resize: (206, 78)->(2366, 896), resolution: (100, 100)=>(1625, 766)
[01:42:22][DEBUG]<airtest.core.api> try match with SURFMatching
[01:42:23][DEBUG]<airtest.aircv.keypoint_base> find_best_result() run time is 1.07 s.
[01:42:23][DEBUG]<airtest.core.api> try match with TemplateMatching
[01:42:23][DEBUG]<airtest.core.api> 'error: in tGenerating HTML log:
无匹配影像，设备连接器也连了Chorme窗体，麻烦各位大大帮忙看看~`

**Comment by yimelia** [comment] 2019-12-26 07:23
Duplicate of https://github.com/AirtestProject/airtest-selenium/issues/6

**Closed as completed by yimelia** 2019-12-26 07:23 UTC
