### ISSUE TITLE
airtest 驱动红米k20时报错 RuntimeError: minicap server setup timeout

### ISSUE THREAD

**Issue by 450679676** [AirtestProject/AirtestIDE#623] opened 2019-11-27 05:10 UTC
系统安卓:8 
MUI :11.0.3

链接设备运行时提示:RuntimeError: minicap server setup timeout

**Comment by yimelia** [comment] 2019-11-27 05:56
Duplicate of #592

**Closed as completed by yimelia** 2019-11-27 05:56 UTC
