### ISSUE TITLE
手机无法连接上airtest，报\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so': No such file or directory\r\n"] stderr[b'']

### ISSUE THREAD

**Issue by xiaofeifeibufei** [AirtestProject/AirtestIDE#648] opened 2019-12-12 06:50 UTC
airtest.core.error.AdbError:E:\绿色\桌面\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 7b2953f wait-for-device stdout[b"adb: error: cannot stat 'E:\\\xe7\xbb\xbf\xe8\x89\xb2\\\xe6\xa1\x8c\xe9\x9d\xa2\\AirtestIDE_2019-09-10_py3_win64\\AirtestIDE_2019-09-11_py3_win64\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so': No such file or directory\r\n"] stderr[b'']

**Comment by yimelia** [comment] 2019-12-12 06:57
Duplicate of #504

Android10问题请参考 https://github.com/AirtestProject/Airtest/pull/618

**Closed as completed by yimelia** 2019-12-12 06:57 UTC
