### ISSUE TITLE
Airtest Generate HTML Error

### ISSUE THREAD

**Issue by phantomsom** [AirtestProject/AirtestIDE#502] opened 2019-08-16 08:01 UTC
**Describe the bug**
Generate HTML Report failed, after a test has finished.

**Screenshots**
A **screenshot** is strongly recommended. Please include both AirtestIDE window and the **black console window**.
![image](https://user-images.githubusercontent.com/19833754/63152669-f3111880-c03e-11e9-9eb5-4fe924ef805c.png)

![image](https://user-images.githubusercontent.com/19833754/63152589-cb21b500-c03e-11e9-855f-cf59641d8bcb.png)

**Expected behaviour**
HTML Report should be generated

**AirtestIDE version:** `1.2.1`

**Platform:** `Windows7 64bit, etc.`

**Comment by yimelia** [comment] 2019-08-19 01:40
duplicate of #487 

sorry for this bug, try to download a preview version of IDE from this [link](https://top.gdl.netease.com/AirtestIDE_2019-06-24_py3_win64_CompatibilityMode.zip), and double click the `.bat` to launch may solve your problem.

**Comment by phantomsom** [comment] 2019-08-29 17:15
Thank you, it solved my problem

**Closed as completed** 2019-09-11 03:46 UTC
Labels: to be released
